spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

# Caminho customizado para a API docs
springdoc.api-docs.path=/api-docs

# Caminho customizado para o Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Habilitar ou desabilitar a API docs
springdoc.api-docs.enabled=true

# Habilitar ou desabilitar o Swagger UI
springdoc.swagger-ui.enabled=true